[project]
name = "py-iorpms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.125.0",
    "pydantic>=2.12.5",
    "pyinstaller>=6.17.0",
    "pyserial>=3.5",
    "uvicorn>=0.38.0",
]
